apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: angular-container
          image: frotend-employee # Aapki image ka naam
          imagePullPolicy: Never # Local image use karne ke liye zaroori hai
          ports:
            - containerPort: 80 # Nginx port

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # Browser mein access ke liye port
  type: NodePort
